#!/usr/bin/env node
import path from 'node:path';
import fs from 'node:fs';
import readline from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import { createStore, load, save, id, now, clamp, dateOnly, titleCase, getSubject, topicBy, topicSubject, subjectProgress, dueStatus, writeNote, git, gitSetup, gitStatus, gitPull, gitPush } from './core.js';

const ROOT = process.env.VEX_HOME || path.join(process.cwd(), '.vex');
const store = createStore(ROOT);
const colors = { reset:'\x1b[0m', cyan:'\x1b[36m', green:'\x1b[32m', yellow:'\x1b[33m', red:'\x1b[31m', dim:'\x1b[2m', bold:'\x1b[1m', magenta:'\x1b[35m' };
const c = (color, text) => `${colors[color] ?? ''}${text}${colors.reset}`;
const clear = () => output.write('\x1b[2J\x1b[H');
const bar = (value, width = 22) => { const filled = Math.round(clamp(value) / 100 * width); return c('cyan', '█'.repeat(filled)) + c('dim', '░'.repeat(width - filled)); };
const pad = (value, n) => String(value).padEnd(n);
const average = values => values.length ? Math.round(values.reduce((a,b) => a + b, 0) / values.length) : 0;
const priorityIcon = p => p === 'high' ? c('red', '●') : p === 'medium' ? c('yellow', '●') : c('green', '●');
const statusIcon = s => s === 'complete' ? c('green', '✓') : s === 'in-progress' ? c('yellow', '→') : c('dim', '·');
let db;
let activePrompt = false;
let actionRunning = false;
let dashboardHandler;
const scriptedMode = !input.isTTY && ['add', 'update', 'done'].includes(process.argv[2]);
const scriptedAnswers = scriptedMode ? fs.readFileSync(0, 'utf8').split(/\r?\n/) : null;

function header(label = 'DASHBOARD') { console.log(`${c('cyan', '╭' + '─'.repeat(68) + '╮')}`); console.log(`${c('cyan','│')}  ${c('bold', 'V E X')}  ${c('dim', '· terminal-native study system')} ${c('magenta', label.padStart(44))} ${c('cyan','│')}`); console.log(`${c('cyan', '├' + '─'.repeat(68) + '┤')}`); }
function footer() { console.log(`${c('cyan','╰' + '─'.repeat(68) + '╯')}`); }
function drawDashboard() { clear(); header(); if (!db.topics.length) { console.log(`│\n│  ${c('bold','Welcome to VEX.')}`); console.log(`│  Press ${c('cyan','a')} to add your first topic.`); console.log('│'); footer(); return; } const subjects = db.subjects.filter(s => db.topics.some(t => t.subjectId === s.id)); console.log('│\n│  ' + c('bold','SUBJECT PROGRESS')); subjects.slice(0,4).forEach(s => console.log(`│  ${pad(s.name.toUpperCase(),14)} ${bar(subjectProgress(db,s),28)}  ${String(subjectProgress(db,s)).padStart(3)}%`)); console.log('│\n│  ' + c('bold','TODAY')); db.topics.filter(t=>t.status!=='complete').sort((a,b)=>(b.priority==='high')-(a.priority==='high')).slice(0,4).forEach(t=>console.log(`│  ${statusIcon(t.status)} ${pad(t.title,30)} ${c('dim',`${topicSubject(db,t)} · ${t.completion}%`)}`)); console.log('│\n│  ' + c('bold','REVISION QUEUE')); const queue=db.topics.filter(t=>t.nextReview&&t.nextReview<=dateOnly()).slice(0,4); (queue.length?queue:db.topics.filter(t=>t.confidence!=='high').slice(0,4)).forEach(t=>{const [label,color]=dueStatus(t);console.log(`│  ${priorityIcon(t.priority)} ${pad(t.title,30)} ${c(color,label)}`);}); console.log('│\n│  '+c('dim','[a] add  [u] update  [r] review  [f] focus  [s] stats  [i] inbox  [g] git  [h] help  [q] quit')); footer(); }
function view(label, lines) { clear(); header(label); lines.forEach(line => console.log(`│${line}`)); footer(); }

async function prompt(question, fallback = '') { activePrompt = true; try { if (scriptedAnswers) return (scriptedAnswers.shift() ?? '').trim() || fallback; if (!prompt.rl) prompt.rl = readline.createInterface({ input, output, terminal: true }); const answer = (await prompt.rl.question(`${question}${fallback ? ` ${c('dim',`[${fallback}]`)}` : ''}: `)).trim(); return answer || fallback; } finally { activePrompt = false; } }
async function choose(question, values, fallback = values[0]) { console.log(question); values.forEach((v,i)=>console.log(`  ${i+1}. ${v}`)); const n=Number(await prompt('Choose','1')); return values[n-1] ?? fallback; }
async function addTopic(rawTitle) { const title=rawTitle||await prompt('Topic title'); if(!title)return; const subjectName=titleCase(await prompt('Subject','General')); let subject=getSubject(db,subjectName); if(!subject){subject={id:id(),name:subjectName,createdAt:now()};db.subjects.push(subject);} const chapter=await prompt('Chapter','General'); const status=await choose('Status',['not-started','in-progress','complete']); const completion=clamp(await prompt('Completion %',status==='complete'?'100':'0')); const priority=await choose('Importance',['high','medium','low'],'medium'); const confidence=await choose('Confidence',['low','medium','high'],'medium'); const nextReview=await prompt('Next review YYYY-MM-DD',dateOnly(new Date(Date.now()+7*86400000))); const topic={id:id(),title,subjectId:subject.id,chapter,status,completion,priority,confidence,accuracy:null,pyqs:0,mistakes:0,revisionCount:0,nextReview,createdAt:now(),updatedAt:now()};db.topics.push(topic);writeNote(store,title,subject.name,chapter,completion);save(store,db);console.log(c('green','✓ Topic added.')); }
async function updateTopic(query) { const t=topicBy(db,query||await prompt('Topic to update'));if(!t)return console.log(c('red','Topic not found.'));t.completion=clamp(await prompt('Completion %',t.completion));t.status=t.completion>=100?'complete':t.completion>0?'in-progress':'not-started';t.confidence=await choose('Confidence',['low','medium','high'],t.confidence);t.accuracy=clamp(await prompt('PYQ accuracy %',t.accuracy??0));t.pyqs=Number(await prompt('PYQs solved',t.pyqs));t.updatedAt=now();if(t.completion>=100){t.revisionCount++;t.nextReview=dateOnly(new Date(Date.now()+7*86400000));}save(store,db);console.log(c('green','✓ Topic updated.')); }
function reviewView(){const lines=['','  '+c('bold','REVISION QUEUE')];const list=db.topics.filter(t=>t.nextReview).sort((a,b)=>a.nextReview.localeCompare(b.nextReview));if(!list.length)lines.push('','  No revision schedule yet.');list.forEach(t=>{const[label,color]=dueStatus(t);lines.push(`  ${priorityIcon(t.priority)} ${pad(t.title,32)} ${c(color,label)}`,`     ${c('dim',`${topicSubject(db,t)} · confidence ${t.confidence} · accuracy ${t.accuracy??'—'}%`)}`);});view('REVISION',lines);}
function statsView(){const lines=['','  '+c('bold','OVERVIEW'),`  Topics           ${db.topics.length}`,`  Completed        ${db.topics.filter(t=>t.status==='complete').length}`,`  Study sessions   ${db.sessions.length}`,`  Total focus time ${Math.round(db.sessions.reduce((a,s)=>a+s.minutes,0))} min`,'','  '+c('bold','WEAK AREAS')];db.topics.slice().sort((a,b)=>a.completion-b.completion).slice(0,5).forEach((t,i)=>lines.push(`  ${i+1}. ${pad(t.title,28)} ${bar(t.completion,16)} ${t.completion}%`));view('ANALYTICS',lines);}
function inboxView(){const lines=['','  '+c('bold','INBOX')];if(!db.inbox.length)lines.push('','  Inbox empty.');else db.inbox.forEach((x,i)=>lines.push(`  ${i+1}. ${x.done?'✓':'→'} ${x.text}`));view('INBOX',lines);}
function gitView(){const s=gitStatus(process.cwd());view('GIT', ['',`  Status: ${s.files||'working tree clean'}`,`  Remote: ${s.remote||'not configured'}`,'','  CLI sync:','  vex git setup <github-url>','  vex git pull','  vex git push']);}
async function focusTopic(query){const t=topicBy(db,query||await prompt('Focus topic'));if(!t)return console.log(c('red','Topic not found.'));const mins=Number(await prompt('Session length (minutes)','25'));console.log(`\n${c('cyan','FOCUS MODE')} · ${t.title}\n`);const start=Date.now();for(let left=mins*60;left>0;left--){process.stdout.write(`\r  ${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}  ${bar((1-left/(mins*60))*100,30)}`);await new Promise(r=>setTimeout(r,1000));}db.sessions.push({id:id(),topicId:t.id,minutes:Math.round((Date.now()-start)/60000),date:dateOnly()});save(store,db);console.log(`\n${c('green','✓ Session complete.')}`);}
function help(){console.log(`\n${c('bold','VEX commands')}\n  vex                         Full-screen dashboard\n  vex add "Topic"             Add topic\n  vex update "Topic"          Update topic\n  vex review | stats | weak   Study views\n  vex focus "Topic"           Focus timer\n  vex inbox "thought"         Capture thought\n  vex git setup <url>          Connect GitHub\n  vex git status|pull|push     Synchronize study data\n\nDashboard keys: a add · u update · r review · f focus · s stats · i inbox · g git · h help · q quit\n`);}
function gitCommand(action,url){if(action==='setup'){if(!url)return console.log('Usage: vex git setup <github-repository-url>');const result=gitSetup(url);console.log(result.commit);console.log(c('green','✓ GitHub remote configured.'));return;}if(action==='status'){const s=gitStatus();console.log(s.files||'Working tree clean.');console.log(`Remote: ${s.remote}`);return;}if(action==='pull')return console.log(gitPull());if(action==='push')return console.log(gitPush());console.log('Usage: vex git setup <url> | status | pull | push');}
async function launch(){if(!input.isTTY||!output.isTTY)return drawDashboard();output.write('\x1b[?1049h\x1b[?25l');input.setRawMode(true);input.resume();drawDashboard();let stopping=false;const quit=()=>{if(stopping)return;stopping=true;input.setRawMode(false);input.pause();input.off('data',dashboardHandler);prompt.rl?.close();output.write('\x1b[?1049l\x1b[?25h');};dashboardHandler=async chunk=>{if(actionRunning||activePrompt)return;const key=String.fromCharCode(chunk[0]).toLowerCase();if(key==='q'||chunk[0]===3){quit();return;}const action={a:()=>addTopic(),u:()=>updateTopic(),r:()=>reviewView(),f:()=>focusTopic(),s:()=>statsView(),i:()=>inboxView(),g:()=>gitView(),h:()=>{clear();help();}}[key];if(!action)return;actionRunning=true;try{if(['a','u','f'].includes(key)){input.setRawMode(false);input.pause();clear();await action();if(key!=='f')await prompt('Press Enter to return');prompt.rl?.close();prompt.rl=null;input.setRawMode(true);input.resume();drawDashboard();}else{action();}}catch(e){input.setRawMode(false);input.pause();console.error(c('red',e.message));await prompt('Press Enter to return');prompt.rl?.close();prompt.rl=null;input.setRawMode(true);input.resume();drawDashboard();}finally{actionRunning=false;}};input.on('data',dashboardHandler);process.once('exit',quit);}

async function main(){const [command,...rest]=process.argv.slice(2);db=load(store);if(!command)return launch();if(command==='help'||command==='--help')return help();if(command==='init')return console.log(`Initialized ${ROOT}`);if(command==='add')return addTopic(rest.join(' ').replace(/^['"]|['"]$/g,''));if(command==='update'||command==='done')return updateTopic(rest.join(' '));if(command==='today')return drawDashboard();if(command==='review')return reviewView();if(command==='stats')return statsView();if(command==='weak')return db.topics.slice().sort((a,b)=>a.completion-b.completion).slice(0,5).forEach((t,i)=>console.log(`${i+1}. ${t.title} — ${t.completion}% completion, ${t.confidence} confidence`));if(command==='search'){const q=rest.join(' ').toLowerCase();const found=db.topics.filter(t=>`${t.title} ${t.chapter} ${topicSubject(db,t)}`.toLowerCase().includes(q));found.forEach(t=>console.log(`${statusIcon(t.status)} ${t.title} — ${topicSubject(db,t)} · ${t.completion}%`));if(!found.length)console.log('No matches.');return;}if(command==='focus')return focusTopic(rest.join(' '));if(command==='inbox'){if(rest.length){db.inbox.push({id:id(),text:rest.join(' '),createdAt:now(),done:false});save(store,db);return console.log(c('green','✓ Added to inbox.'));}return inboxView();}if(command==='git')return gitCommand(rest[0],rest[1]);console.log(`Unknown command: ${command}`);help();}
main().catch(e=>{console.error(c('red',e.message));process.exitCode=1;});
